# Generated by Django 2.0.2 on 2020-09-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('step', models.IntegerField()),
                ('tag', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
