# Generated by Django 2.0.2 on 2020-09-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_auto_20200921_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
