# Generated by Django 2.0.2 on 2020-11-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_auto_20200921_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
